server:
  port: 8082

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5456/payment_db
    username: payment_user
    password: payment_pass
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration/payment
  kafka:
    bootstrap-servers: localhost:9094

payments:
  fake-enabled: true
  toss:
    base-url: https://api.tosspayments.com
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
