server:
  port: 8082

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5456/payment_db
    username: payment_user
    password: payment_pass
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9094
